name: Build and Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.20.2'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: |
        rm -rf dist  # Menghapus folder dist jika ada
        npm run build

    - name: Deploy to gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Buat direktori baru untuk struktur yang diinginkan
        mkdir -p autonity/js autonity/css
        mv dist/js/* autonity/js/ || echo "No JS files to move"
        mv dist/css/* autonity/css/ || echo "No CSS files to move"
        mv dist/index.html . || echo "No index.html to move"
        mv dist/favicon.ico . || echo "No favicon.ico to move"
        
        # Inisialisasi repository git baru dan checkout ke branch gh-pages
        git init
        git config --local user.email "test@test.com"
        git config --local user.name "test"
        git remote remove origin || echo "No remote origin to remove"
        git remote add origin https://github.com/${{ github.repository }}
        git fetch origin
        git checkout -b gh-pages origin/gh-pages || git checkout --orphan gh-pages
        
        # Menghapus semua file di branch gh-pages
        git rm -rf .
        git clean -fdx
        
        # Memindahkan file ke branch gh-pages
        mv ../autonity/js autonity/js || echo "No JS files to move"
        mv ../autonity/css autonity/css || echo "No CSS files to move"
        mv ../index.html index.html || echo "No index.html to move"
        mv ../favicon.ico favicon.ico || echo "No favicon.ico to move"
        
        # Menambahkan file ke git
        git add autonity/js autonity/css index.html favicon.ico
        git commit -m "Deploy to gh-pages"
        git push --force origin gh-pages
        
        # Bersihkan direktori kerja
        rm -rf autonity js css index.html favicon.ico
